### PR TITLE
Improve GUI for Positions and Configurations

### PR DESCRIPTION
**Pull request by jrheinlaender**
The context menu for Configurations is now available on non-Android platforms.
It is now possible to edit existing Positions.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
> Do you know what the problem is with the linux build checks above yet? I haven't looked in detail yet.

Aah!  Never mind.  I see it's the dreaded 'CLOUDSMITH_API_KEY must be set in the build environment' error.  @rgleason might be able to help with that.  I believe it has to do with the setup of this repo, which belongs to him.  I have no idea why it doesn't seem to affect the macos and windows builds.

I'll get on with the code review and manual tests in the mean time.  Let me know which platforms you've already tested on, and I can try to fill the gaps.  I have access to macos, debian, windows and android.

**Comment by jrheinlaender** [comment]
Thank you for all the feedback. 

@quinton-hoole  My platform is Ubuntu Desktop. I don't have any other platforms set up. Also, I couldn't see a "make check" or "make test" target in the plugin, so I am doing manual testing only. My hope was that CircleCi would do the testing for me...

@rgleason My contributions will probably be sporadic, so I am fine with limited rights.

What is the platform to ask general questions about the code?

File: src/WeatherRouting.cpp [hunk 1]
```diff
@@ -1292,6 +1295,43 @@ void WeatherRouting::OnEditConfiguration() {
 #endif
 }
 
+void WeatherRouting::OnEditPosition() {
```
Comment (quinton-hoole) [inline src/WeatherRouting.cpp]: I though you mentioned that this code already exists for Android?  Can't we use the existing code?

**Comment by quinton-hoole** [comment]
@jrheinlaender Your code looks pretty good. Thanks!  Just one comment/question. 
I'll try to test it on a few other platforms tomorrow, and get the automated CI builds and unit tests to run across all platforms.

**Comment by quinton-hoole** [comment]
My apologies for the delays in getting this PR merged. I've been busy with other things.  Also, I ran into some compilation errors when trying to build this PR for testing. I haven't had time to track down the root cause yet.  Has anyone else run into this problem?  It looks like opencpn-libs has been updated in a non-backwards-compatible way.

```
/Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:144:3: error: unknown type name 'wxPlugin_WaypointListNode'; did you mean 'Plugin_WaypointList'?
  144 |   wxPlugin_WaypointListNode* pwpnode = proute->pWaypointList->GetFirst();
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
      |   Plugin_WaypointList
/Users/quinton/src/OpenCPN-dev/weather_routing_pi/opencpn-libs/api-18/ocpn_plugin.h:2347:34: note: 'Plugin_WaypointList' declared here
 2347 | WX_DECLARE_LIST(PlugIn_Waypoint, Plugin_WaypointList);
      |                                  ^
/Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:144:30: error: no viable conversion from 'compatibility_iterator' to 'Plugin_WaypointList *'
  144 |   wxPlugin_WaypointListNode* pwpnode = proute->pWaypointList->GetFirst();
      |                              ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/include/wx-3.3/wx/list.h:119:9: note: candidate function
  119 |         operator bool() const
      |         ^
/Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:164:20: error: no member named 'GetData' in 'Plugin_WaypointList'
  164 |     pwp = pwpnode->GetData();

```

**Comment by quinton-hoole** [comment]
cc @jrheinlaender @rgleason ^^

**Comment by rgleason** [comment]
@quinton-hoole  Didn't you accept my invite to Circleci?

**Comment by jrheinlaender** [comment]
I can't reproduce this on my system, but an easy fix would be to write "auto" instead of "wxPlugin_WaypointListNode*" and hope for the best...

> /Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:144:3: error: unknown type name 'wxPlugin_WaypointListNode'; did you mean 'Plugin_WaypointList'?
>   144 |   wxPlugin_WaypointListNode* pwpnode = proute->pWaypointList->GetFirst();

I would suspect an incompatible change in the WX_DECLARE_LIST macro (wx/list.h), since the types are generated there.

**Comment by quinton-hoole** [comment]
> > @quinton-hoole Didn't you accept my invite to Circleci?
> 
> 
> 
> @rgleason I am not aware that I have received such an invitation.  I checked in my email.  Where would I find such an invitation?  Please resend as needed, and tell me where to look.
> 
> 
> 
> I think it was an email. I will go back and resend it. I sent it to you and sebastien.

@rgleason it appears that I already have a circleci account, and that it is already part of your circleci organization. But irrespective of that, it's not clear what that has to do with the current issue being reported and discussed here. 
Could you please read this thread carefully, and explain what my circleci membership has to do with @jrheinlaender's PR?  I'm very confused.

**Comment by rgleason** [comment]
I used reply

**Comment by rgleason** [comment]
> My apologies for the delays in getting this PR merged. I've been busy with other things. Also, I ran into some compilation errors when trying to build this PR for testing. I haven't had time to track down the root cause yet. Has anyone else run into this problem? It looks like opencpn-libs has been updated in a non-backwards-compatible way.
> 
> /Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:144:3: error: unknown type name 'wxPlugin_WaypointListNode'; did you mean 'Plugin_WaypointList'?
>   144 |   wxPlugin_WaypointListNode* pwpnode = proute->pWaypointList->GetFirst();
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
>       |   Plugin_WaypointList
> /Users/quinton/src/OpenCPN-dev/weather_routing_pi/opencpn-libs/api-18/ocpn_plugin.h:2347:34: note: 'Plugin_WaypointList' declared here
>  2347 | WX_DECLARE_LIST(PlugIn_Waypoint, Plugin_WaypointList);
>       |                                  ^
> /Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:144:30: error: no viable conversion from 'compatibility_iterator' to 'Plugin_WaypointList *'
>   144 |   wxPlugin_WaypointListNode* pwpnode = proute->pWaypointList->GetFirst();
>       |                              ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /opt/homebrew/include/wx-3.3/wx/list.h:119:9: note: candidate function
>   119 |         operator bool() const
>       |         ^
> /Users/quinton/src/OpenCPN-dev/weather_routing_pi/src/RouteMapOverlay.cpp:164:20: error: no member named 'GetData' in 'Plugin_WaypointList'
>   164 |     pwp = pwpnode->GetData();
> 
> 


###  It looks like opencpn-libs has been updated in a non-backwards-compatible way.

Quinton, was this problem ever resolved?
I do suspect something has changed in opencpn-libs because a dev version of WR from api118 branch does not work in Opencpn 5.12.4 release.  See Api118 plugin fails in O5.12.4 but works in MSVS Debug with O5.13 current master #466

**Comment by quinton-hoole** [comment]
@rgleason no, this is not yet resolved. I've been busy with other things.
This is a compilation error, not a runtime error. I only noticed it since I performed a 'git submodule update'. I reverted that but still see the problem. I'm not sure we're handling submodules correctly. I think we're supposed to commit a record of the specific version of the submodule to our repo, so that the correct one gets downloaded. But I think we're just pulling the latest version of the submodule. Which can't work. I think the build script is broken. But I haven't had time to diagnose and fix the problem yet.

**Comment by bdbcat** [comment]
Rick...
I'll bump the priority in my queue.  Do nothing radical, yet, please.

**Comment by quinton-hoole** [comment]
> @bdbcat  
> 
> 
> 
> I am going to have to revert everything if this is not fixed.
> 
> This problem has gone on too long and will get harder and harder to fix. 
> 
> I am unwilling to let it go on longer and Sebastien does not seem to be responding either.
> 
> 
> 
> We need to keep WR fully operational and I need to update the plugin once this problem is resolved, or just revert to some unknown point.
> 
> 
> 
> The problem I am talking about is here
> 
> Api118 plugin fails in O5.12.4 but works in MSVS Debug with O5.13 current master https://github.com/rgleason/weather_routing_pi/issues/466
> 
> 
> 
> Quinton, I am ringing the alarm bell here, because this may involve OpenCPN as well, in particular  opencpn-libs which is vital to plugins.

For what it's worth, my guess is:
1. OpenCPN-libs needs to change periodically in non-backwards compatible ways. 
2. Plugins need to consume the specific version of OpenCPN-libs that is compatible with their source code. If plugins try to consume a newer version, compilation and/or runtime errors might occur. 
3. Plugins should resolve the above issues before committing to a newer version of OpenCPN-libs. 
4. I'm not convinced that all plugins are adhering to the above workflow, given the current state of the build infrastructure for this plugins (specifically test_pi). 

I might be wrong about this, but everything I've seen thus far is consistent with the above. If I'm right, then what needs to be done is to fix the plugin build, test and deploy cycle.

**Comment by quinton-hoole** [comment]
Thanks @bdbcat . I was unaware that non-backwards compatible changes to openCPN-libs was not part of the design. I don't understand how that can be tenable over the long term, but if the design is for only backwards-compatible changes, then I can definitely go and track down the culprits.

**Comment by quinton-hoole** [comment]
OK, I finally found some time to fix [this](https://github.com/rgleason/weather_routing_pi/pull/470#issuecomment-3503425861).  WXWidgets3.3 somehow got ahead of WXWidgets3.2 in my path.  Arrgh. Fixed now.   So I can build and test stuff now :-)

**Comment by quinton-hoole** [comment]
I finally am able to build and test this.  So far I've found that there appear to be some rounding errors such that the floating point numbers that are entered are not the the same ones that are persisted.  The floating point numbers remain correct until OpenCPN is restarted, then they change to slightly different numbers. 

Looking at the code, I'd also like to clean up the code a bit so that the code to update and the code to add are distinct. Right now, when I update a position, the code for "AddPosition" gets called, which is a bit confusing.  

I also think we need to ake less use of wxString (as per the wxWidgets guidelines, which say that it's depracated in favor of std:string.  

More later.  I'll have some more concrete suggestions in perhaps a few hours.  For now though, please don't merge this PR until we've addressed the above.

**Comment by jrheinlaender** [comment]
Thanks for your review. The rounding errors are introduced when writing to XML with only 5 digits precision

c->SetAttribute("Latitude", wxString::Format("%.5f", (*it).lat).mb_str());
c->SetAttribute("Longitude", wxString::Format("%.5f", (*it).lon).mb_str());

I could change that to 6 or more. What is the OpenCPN internal format for latitude/longitude? If it is double precision, we should write to XML with double precision, too. Otherwise, there will always be some rounding problems, like 1.19999 appearing instead of 1.2 .

**Comment by rgleason** [comment]
Bdbcat fixed the first primary problem (there are still thread and heap isssues)  so this could be merged now if it is ready. Quinton have you tested it?

**Comment by rgleason** [comment]
@jrheinlaender   We have moved into using the "master" branch. You may not have picked up on that discussion. Sebastien made a request to work out of  the  "master" branch and I agreed.   Sorry. Can you make another PR to  rgleason/master?

Also the same for the other PRs?

I made a PR from Master to yours for the changes to the Master  which disables the GSHHS cache fixing one of the thread issues.  We still have work to do to fix the other thread/heap issues. 
 
Very sorry. Thanks. Rick

**Comment by rgleason** [comment]
Now closing, hope @jrheinlaender  can make a PR to the master branch

**Comment by jrheinlaender** [comment]
> I'd love to get rid of all the wxStrings, Format()

What would you use instead of Format()? C++20 std::format() ?

**Comment by quinton-hoole** [comment]
Well, I don't think that OpenCPN has adopted C++20 yet, but something a bit safer than format strings would be great. C++14 streams should presumably be able to do what you want, in a type-safe way?

There may well also already be methods in the OpenCPN API that do what you want (ToSDMM() etc). I haven't checked. I'm away from my keyboard and on my phone at the moment, so please excuse my vagueness.
